### ISSUE TITLE
Maybe a bug on copy.copy_resource_folder function for sub-package copy

### ISSUE THREAD

**Issue by areysset** [fast-aircraft-design/FAST-OAD#205]
I'm not sure because I try to copy files using that function with void _init_.py in sub-folders.
But **new_package_name = ".".join([package, resource_name])** gives me an error because **package** is not a string.

For my use I changed it to :

    def copy_resource_folder(soucre_path: str, destination_path: str, exclude: List[str] = None, symlinks=False, ignore=None):
    """
    Copies the source folder content into the destination folder, except for
    names in exclusion_list

    :param soucre_path: file system path of source
    :param destination_path: file system path of destination
    :param exclude: list of item names that should not be copied
    """

    exclusion_list = ["__pycache__"]
    if exclude:
        exclusion_list += exclude

    for resource_name in os.listdir(soucre_path):
        source_path = pth.join(soucre_path, resource_name)
        target_path = pth.join(destination_path, resource_name)
        if os.path.exists(target_path):
            try:
                shutil.rmtree(target_path)
            except Exception as message:
                print(message)
                os.unlink(target_path)
        if os.path.isdir(source_path):
            shutil.copytree(source_path, target_path, symlinks, ignore)
        else:
            shutil.copy(source_path, destination_path)

**Comment by christophe-david** [comment]
Could you please give more details on the encountered bug (how you use the function, what is the encountered error message) ?

**Comment by areysset** [comment]
Problem was in fastoad\utils\resource_management\copy.py line 72
Something like **blablabla join inputs should be string** while we give Package!

**Comment by christophe-david** [comment]
Please be more specific so we can have a chance to understand what's going on. At least a piece of the code you use and the **exact** error message.

**Comment by areysset** [comment]
Try whatever you want like:

import fastoad
from fastoad.utils.resource_management.copy import copy_resource_folder

copy_resource_folder(fastoad, "D:\\")

You will obtain:

  File "C:\ProgramData\Anaconda3\lib\site-packages\fastoad\utils\resource_management\copy.py", line 72, in copy_resource_folder
    new_package_name = ".".join([package, resource_name])

TypeError: sequence item 0: expected str instance, module found

**Comment by christophe-david** [comment]
Ok, now we can discuss :)

I would say the main problem with the current function is that the type hint is wrong and should be `str` (docstring gives a better advice, though).

It will work better if you do
```python
from fastoad.utils.resource_management.copy import copy_resource_folder

copy_resource_folder("fastoad", "D:\")
```
Actually, it fails because of some IPython import, but in a realistic case with a real resource folder, it works.

Also, be aware that the solution in your first post cannot replace the current function of FAST-OAD.  
The point of using `importlib_resources` (or `importlib.resources` for Python 3.7+) is to access resource files even if they do not exist as as physical files nor directories on the file system (which can happen when package is installed as an archive).
Your solution **needs** physical files and directories (which may be fine for any local component you don't intend to package, though).

Finally, the fact that you modified this function suggests that you copied FAST-OAD code instead of just using it after a `pip install`. Though it is perfectly fine (that's the open-source way!), be aware that you could get better support if you use FAST-OAD as an external package and just add your own models.

In case you encounter a bug or a missing feature, you can raise an issue, or even propose a solution through the usual [fork process](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo).

My point is that it is better to enhance together FAST-OAD rather than having multiple versions of it.
