### ISSUE TITLE
Upgrade to FAST-OAD 1.0.0 not successfull

### ISSUE THREAD

**Issue by AleSgueglia** [fast-aircraft-design/FAST-OAD#306]
Hello, 
I open this issue because I tried to update my fast-oad version to the latest release. 
Through the Anaconda prompt I run "pip install --upgrade fast-oad" but the code is not installed. 
The following error appears:  

"Attempting uninstall: ruamel.yaml
    Found existing installation: ruamel-yaml 0.15.87
ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

I tried to manually uninstall the package ruamel.yaml but this does not solve the issue. 

Thanks in advance for any help to solve the issue. 

Regards,
Alessandro Sgueglia

**Comment by christophe-david** [comment]
Hi,

It looks like Anaconda comes with a "clone" of `ruamel.yaml` (`ruamel_yaml` and a kind of alias `ruamel-yaml`). Apparently, it is not a problem with the old version of Anaconda I had, but with the latest one, I get the same problem as you. It looks impossible to either upgrade or uninstall this package and IMHO, it is a bug in Anaconda install.

As a workaround, I would advise that you create a new virtual environment (possible through command line, but you may also do it through GUI using Anaconda navigator, see image below).
Actually, I think this a good solution, even without the `ruamel.yaml` problem, especially because FAST-OAD brings some big [changes](https://github.com/fast-aircraft-design/FAST-OAD/releases/tag/v1.0.0) compared to 0.5.4b. 
Then the advantage of the virtual environment is double:
- you keep your current working environment (with FAST-OAD 0.5.4b) untouched
- you will not get this `pip` error, since `ruamel-yaml` will not be in your new environment.

_____
_____
_Virtual environment though anaconda navigator..._

<img width="1016" alt="conda" src="https://user-images.githubusercontent.com/49477099/114355152-6a2de580-9b6f-11eb-96f4-3e2534d13e2f.png">

**Comment by younes-jc** [comment]
The solution @christophe-david mentioned worked for me. However, when trying to run any of the notebooks I get the following error (for the image below, I tried to execute the first code cell of "01_tutorial", but the same error appears for "CeRAS_case_study" notebook):

![image](https://user-images.githubusercontent.com/82504418/114856458-6c9a7480-9de7-11eb-9a70-bc1e28ab3e1b.png)

Maybe it's taking a wrong path to the fastoad installation: as you can see in the image, it yields "c:\users\UserName\anaconda3\lib\site-packages\fastoad" instead of "C:\Users\UserName\anaconda3\envs\EnvName\Lib\site-packages\fastoad". To run the notebook, I have opened the terminal using the anaconda navigator, from the respective environment created to install fast-oad 1.0.0:

![image](https://user-images.githubusercontent.com/82504418/114856579-8dfb6080-9de7-11eb-941f-3bf8b1b62326.png)

**Comment by christophe-david** [comment]
Indeed, there is a strange mix of environment.

As you noticed, the used code is not at the right location. I can add the used code is not at the right **version** of FAST-OAD: the path `models/performances/breguet` do not exist anymore in FAST-OAD 1.0.

Could you please post the result of the command `fastoad list_modules` ? (Please copy/paste the text instead of providing a screen capture. Text is easier to analyze)

**Comment by younes-jc** [comment]
I'm afraid I won't be able to do that. As you pointed out, I decided to uninstall Anaconda to install an older version (2019.10 in my case). FAST-OAD 1.0.1 can then be installed without any issues :)

I think the problem I posted can be solved by launching Jupyter extension from the new environment "EnvName" by default (path "C:\Users\UserName\anaconda3\envs\EnvName\Lib\site-packages\jupyterlab"), but I didn't manage to do that so I decided to uninstall everything and start over.

**Comment by christophe-david** [comment]
Too bad, then.

For the record, I came across this [bug report in Anaconda](https://github.com/conda/conda/issues/10178) that is clearly linked to the current issue.

Nevertheless, FAST-OAD 1.0.2 is on its way, where we lower the version requirement for `ruamel.yaml`, to prevent Anaconda from trying and failing to update its `ruamel_yaml`.

**Comment by christophe-david** [comment]
FAST-OAD 1.0.2 is out!
It should avoid the Anaconda bug by not triggering update of `ruamel.yaml`.
