### ISSUE TITLE
Variable description in components are lost in .xml files

### ISSUE THREAD

**Issue by ScottDelbecq** [fast-aircraft-design/FAST-OAD#319]
It is possible to provide a description to variables through the kwarg `desc` of `self.add_input()` or `self.add_output()` in OpenMDAO components. However, this description is lost when generating the input or output .xml files since recent releases.

**Comment by Martin-Delavenne** [comment]
The same seems to occur with the units which are only promoted to the output file for output variables as illustrated with attached files. (In the attached captures descriptions appear because au variabble_descriptions.txt file was added). 
<img width="401" alt="Capture1" src="https://user-images.githubusercontent.com/73106350/117124973-45f1ad00-ad99-11eb-88f2-3a15b5ad3742.PNG">
<img width="497" alt="Capture2" src="https://user-images.githubusercontent.com/73106350/117124981-47bb7080-ad99-11eb-993d-dc6ed8f73777.PNG">
<img width="498" alt="Capture3" src="https://user-images.githubusercontent.com/73106350/117125259-95d07400-ad99-11eb-8941-31794592d5a4.PNG">
