### ISSUE TITLE
Add alternative engine settings

### ISSUE THREAD

**Issue by vinx012** [fast-aircraft-design/FAST-OAD#342]
Hello, 

I am looking for an easy way to add some engine settings to the ones already defined. I tried inheriting the class, but it doesn't let me add another engine setting. I get an error which says : "Cannot extend enumerations". Is there a specific method which does that?

Thanks,
Vincenzo

**Comment by christophe-david** [comment]
Good question. Actually, we did not anticipate this usage.

Your question made me find [this post](https://stackoverflow.com/a/33680929), that advertises the Advanced Enumeration ([aenum](https://pypi.python.org/pypi/aenum)) library.

We should probably use it instead of the standard [enum](https://docs.python.org/3/library/enum.html). That could be done quickly enough.
