### ISSUE TITLE
Defining input variables within .xml as a vector and inheriting shape in models (shape_by_conn) is not working.

### ISSUE THREAD

**Issue by areysset** [fast-aircraft-design/FAST-OAD#354]
The problem occurs when writing the needed inputs in the process by doing:
_problem = self.get_problem(read_inputs=False)
problem.setup()_

The setup tries to _setup_dynamic_shapes without the ivc relative to .xml inputs and fail.
But even trying  self.get_problem(read_inputs=True) leads to the same error since we try first to setup the problem without the input file.

**Comment by christophe-david** [comment]
Ok you win, you have proven we definitely need templates for the bug reports.
So I have just set up that.

Would you please open again this issue and fill in the proper template ?

Also, please keep in mind that a thorough description of what **you** do and what you get will always be far more valuable that any attempt to show where the problem is in our code (we'll get this information anyway if you simply copy-paste the complete error message you get).
