### ISSUE TITLE
Some variable_descriptions.txt are not read in custom plugin

### ISSUE THREAD

**Issue by florentLutz** [fast-aircraft-design/FAST-OAD#378]
**Describe the bug**
In a custom FAST-OAD plugin, variable_descriptions.txt are only read if they are next to a module registered using @RegisterOpenMDAOSystem. I'm not sure if this behaviour is expected.

**To Reproduce**
With files in this [archive](https://github.com/fast-aircraft-design/FAST-OAD/files/6901018/VariableDescriptionBehaviourReproduction.zip), the following appears when running the main.py file : 

![Actual Behaviour](https://user-images.githubusercontent.com/66668699/127505394-4f45d9d3-fd06-4665-87d2-107e9c3136cf.PNG)

**Expected behavior**
Since there is another variable_descriptions.txt in the src/model folder (which a priori is not read), the expected behaviour would have been :

![Expected Behaviour](https://user-images.githubusercontent.com/66668699/127505923-f7a10abe-8cb4-45bb-b8ed-751c63328221.PNG)

**Error message**
There are no error messages.

**Environment**
- Operating System: Windows 10
- Python environment: Python 3.9.0
- Packages: FAST-OAD 1.0.4, OpenMDAO 3.9.2

**Additionnal context** 
Same behaviour is seen in FAST-GA, the variable_descriptions.txt in fastga/src/models is not read while the one in fastga/src/models/aerodynamics for exemple is read. If we add this [file](https://github.com/fast-aircraft-design/FAST-OAD/files/6901152/variable_description_register.zip) the problem is solved. If the reviewer wants it, we can create a branch to see the "problem" in a more complex context

**Comment by florentLutz** [comment]
It indeed worked as you explained, thank you for the explanation and the time provided.

There is however a similar behaviour in FAST-OAD-GA, albeit the module_folder is left empty in the .yml, as written in the **Additionnal context** section of the issue.

I'll try to write a simple code to replicate the behaviour. In the meantime, a workaround has been found, so there is no urgent need for an answer.

Thanks again for the help.

**Comment by florentLutz** [comment]
I managed to replicate the issue with this [code](https://github.com/fast-aircraft-design/FAST-OAD/files/6916929/VariableDescriptionBug.zip). It is mostly the same as before except now the modules are declared as a plugin. Consequently, module_folder is not used anymore and the behaviour displayed in the first message of the issue is seen.

From what I've tried, it seems that only the `variable_descriptions.txt` next to a file containing a @RegisterOpenMDAOSystem are read. This observation prompted the workaround that can be seen in FAST-OAD-GA.

I ran the code with a conda environement with Python 3.8 and did a `poetry install` in a separate folder on my computer which gave the same behaviour. Do I need to write a separate issue for this problem ?

**Comment by christophe-david** [comment]
Thanks for taking the time to do this sample code. Very useful.

I hope you took the time to read the [doc link](https://fast-oad.readthedocs.io/en/v1.0.5/documentation/custom_modules/add_variable_documentation.html#defining-variable-description-in-dedicated-files) I previously provided. In that case, I will greatly appreciate suggestions about how to better formulate the behavior to expect.

The point is that the `variable_descriptions.txt` that is not read is not in the same folder as a registered component, **neither at the root folder of the plugin**.
If I simply change the plugin declaration to `"internal_models" = "variable.model"`, the file is correctly read. Same happens if I keep the plugin declaration unchanged but if I simply move the file to the `variable` folder.
_BTW I would recommend a more specific plugin name. I would not have expected that having the same plugin name as the internal one from FAST-OAD would work._

**Comment by florentLutz** [comment]
Thank you for the reply. I confused the root of the plugin and the root of the models folders, so this is my bad. 

I deleted the file I added as a work around, modified the `pyproject.toml`, and now everything works as expected. 

Thanks again for your time and sorry for wasting it on a confusion on my part.

**Comment by christophe-david** [comment]
No problem. Thanks for the feedback.
